export default [
  {
    id: 586674,
    title: "Three Wise Men Shot",
    image: "https://spoonacular.com/recipeImages/586674-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 0,
    missedIngredients: [],
    usedIngredients: [
      {
        id: 10014052,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Alcoholic Beverages",
        name: "scotch whiskey",
        original: "Johnnie Walker Scotch Whiskey",
        originalString: "Johnnie Walker Scotch Whiskey",
        originalName: "Johnnie Walker Scotch Whiskey",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whiskey-bottle.jpg",
      },
      {
        id: 14052,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Alcoholic Beverages",
        name: "whiskey",
        original: "Jim Beam Bourbon Whiskey",
        originalString: "Jim Beam Bourbon Whiskey",
        originalName: "Jim Beam Bourbon Whiskey",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whiskey-bottle.jpg",
      },
      {
        id: 14052,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Alcoholic Beverages",
        name: "whiskey",
        original: "Jack Daniel's Tennessee Whiskey",
        originalString: "Jack Daniel's Tennessee Whiskey",
        originalName: "Jack Daniel's Tennessee Whiskey",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whiskey-bottle.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 66,
  },
  {
    id: 577801,
    title: "Bourbon, Lemon, and Honey",
    image: "https://spoonacular.com/recipeImages/577801-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 19296,
        amount: 1.0,
        unit: "tablespoons",
        unitLong: "tablespoon",
        unitShort: "Tbsp",
        aisle: "Nut butters, Jams, and Honey",
        name: "honey",
        original: "1-2 tablespoons honey*",
        originalString: "1-2 tablespoons honey*",
        originalName: "honey",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/honey.png",
      },
      {
        id: 9152,
        amount: 1.5,
        unit: "ounces",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Produce",
        name: "lemon juice",
        original: "1½ ounces freshly squeezed lemon juice",
        originalString: "1½ ounces freshly squeezed lemon juice",
        originalName: "freshly squeezed lemon juice",
        metaInformation: ["freshly squeezed"],
        meta: ["freshly squeezed"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/lemon-juice.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 10014037,
        amount: 1.5,
        unit: "ounces",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Alcoholic Beverages",
        name: "bourbon",
        original: "1½ ounces good bourbon",
        originalString: "1½ ounces good bourbon",
        originalName: "good bourbon",
        metaInformation: ["good"],
        meta: ["good"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/bourbon.png",
      },
    ],
    unusedIngredients: [
      {
        id: 14052,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Alcoholic Beverages",
        name: "whiskey",
        original: "whiskey",
        originalString: "whiskey",
        originalName: "whiskey",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whiskey-bottle.jpg",
      },
    ],
    likes: 228,
  },
  {
    id: 680641,
    title: "Apple Cider Whiskey Smash",
    image: "https://spoonacular.com/recipeImages/680641-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 1009016,
        amount: 4.0,
        unit: "oz",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Beverages",
        name: "apple cider",
        original: "4oz apple cider",
        originalString: "4oz apple cider",
        originalName: "apple cider",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/apple-cider.jpg",
      },
      {
        id: 9152,
        amount: 0.5,
        unit: "oz",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Produce",
        name: "lemon juice",
        original: "1/2oz lemon juice",
        originalString: "1/2oz lemon juice",
        originalName: "lemon juice",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/lemon-juice.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 14052,
        amount: 1.0,
        unit: "oz",
        unitLong: "ounce",
        unitShort: "oz",
        aisle: "Alcoholic Beverages",
        name: "whiskey",
        original: "1oz whiskey",
        originalString: "1oz whiskey",
        originalName: "whiskey",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whiskey-bottle.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 179,
  },
  {
    id: 205105,
    title: "North End Grill's Bloody Smoky",
    image: "https://spoonacular.com/recipeImages/205105-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 11282,
        amount: 4.0,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Produce",
        name: "onions",
        original: "Pickled onions",
        originalString: "Pickled onions",
        originalName: "Pickled onions",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/brown-onion.png",
      },
      {
        id: 14051,
        amount: 3.0,
        unit: "ounces",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Alcoholic Beverages",
        name: "vodka",
        original: "3 ounces vodka",
        originalString: "3 ounces vodka",
        originalName: "vodka",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/vodka.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 10014052,
        amount: 3.0,
        unit: "ounces",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Alcoholic Beverages",
        name: "scotch",
        original: "3 ounces Islay-style Scotch (such as Laphroaig)",
        originalString: "3 ounces Islay-style Scotch (such as Laphroaig)",
        originalName: "Islay-style Scotch (such as Laphroaig)",
        metaInformation: ["islay-style", "(such as Laphroaig)"],
        meta: ["islay-style", "(such as Laphroaig)"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whiskey-bottle.jpg",
      },
    ],
    unusedIngredients: [
      {
        id: 14052,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Alcoholic Beverages",
        name: "whiskey",
        original: "whiskey",
        originalString: "whiskey",
        originalName: "whiskey",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whiskey-bottle.jpg",
      },
    ],
    likes: 19,
  },
  {
    id: 688212,
    title: "Pumpkin Beer Cocktail",
    image: "https://spoonacular.com/recipeImages/688212-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 10014003,
        amount: 12.0,
        unit: "ounce",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Alcoholic Beverages",
        name: "dark beer",
        original:
          "1 12 ounce bottle of dark beer, or can of your favorite beer, for topping, like molsen xxx",
        originalString:
          "1 12 ounce bottle of dark beer, or can of your favorite beer, for topping, like molsen xxx",
        originalName:
          "dark beer, or can of your favorite beer, for topping, like molsen xxx",
        metaInformation: [
          "dark",
          "for topping, like molsen xxx",
          "your favorite",
          "canned",
        ],
        meta: [
          "dark",
          "for topping, like molsen xxx",
          "your favorite",
          "canned",
        ],
        extendedName: "canned dark beer",
        image: "https://spoonacular.com/cdn/ingredients_100x100/guinness.png",
      },
      {
        id: 1002035,
        amount: 0.5,
        unit: "ounce",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Spices and Seasonings",
        name: "pumpkin spice mix",
        original: "1/2 ounce pumpkin spice liquor",
        originalString: "1/2 ounce pumpkin spice liquor",
        originalName: "pumpkin spice liquor",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/garam-masala.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 14052,
        amount: 0.5,
        unit: "ounce",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Alcoholic Beverages",
        name: "whisky",
        original: "1/2 ounce crown royal whisky",
        originalString: "1/2 ounce crown royal whisky",
        originalName: "crown royal whisky",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whiskey-bottle.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 3,
  },
  {
    id: 219666,
    title: "Mint Julep",
    image: "https://spoonacular.com/recipeImages/219666-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 2064,
        amount: 1.0,
        unit: "sprigs",
        unitLong: "sprig",
        unitShort: "sprigs",
        aisle: "Produce;Spices and Seasonings",
        name: "mint",
        original: "Garnish: fresh mint sprigs",
        originalString: "Garnish: fresh mint sprigs",
        originalName: "Garnish: fresh mint",
        metaInformation: ["fresh"],
        meta: ["fresh"],
        extendedName: "fresh mint",
        image: "https://spoonacular.com/cdn/ingredients_100x100/mint.jpg",
      },
      {
        id: 2064,
        amount: 1.0,
        unit: "tablespoon",
        unitLong: "tablespoon",
        unitShort: "Tbsp",
        aisle: "Produce;Spices and Seasonings",
        name: "mint",
        original: "1 tablespoon Mint Syrup",
        originalString: "1 tablespoon Mint Syrup",
        originalName: "Mint Syrup",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/mint.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 10014037,
        amount: 0.25,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Alcoholic Beverages",
        name: "bourbon",
        original: "1/4 cup bourbon",
        originalString: "1/4 cup bourbon",
        originalName: "bourbon",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/bourbon.png",
      },
    ],
    unusedIngredients: [
      {
        id: 14052,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Alcoholic Beverages",
        name: "whiskey",
        original: "whiskey",
        originalString: "whiskey",
        originalName: "whiskey",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whiskey-bottle.jpg",
      },
    ],
    likes: 0,
  },
  {
    id: 73930,
    title: "Pig’s Nose",
    image: "https://spoonacular.com/recipeImages/73930-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 10093653,
        amount: 1.0,
        unit: "dash",
        unitLong: "dash",
        unitShort: "dash",
        aisle: "Alcoholic Beverages",
        name: "orange bitters",
        original: "1 dash orange bitters",
        originalString: "1 dash orange bitters",
        originalName: "orange bitters",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/dark-sauce.jpg",
      },
      {
        id: 9216,
        amount: 1.0,
        unit: "large strip",
        unitLong: "large strip",
        unitShort: "large strip",
        aisle: "Produce",
        name: "orange zest",
        original: "1 large strip orange zest",
        originalString: "1 large strip orange zest",
        originalName: "orange zest",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/orange-zest.png",
      },
    ],
    usedIngredients: [
      {
        id: 10014052,
        amount: 2.0,
        unit: "oz",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Alcoholic Beverages",
        name: "scotch",
        original: "2 oz scotch",
        originalString: "2 oz scotch",
        originalName: "scotch",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whiskey-bottle.jpg",
      },
    ],
    unusedIngredients: [
      {
        id: 14052,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Alcoholic Beverages",
        name: "whiskey",
        original: "whiskey",
        originalString: "whiskey",
        originalName: "whiskey",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whiskey-bottle.jpg",
      },
    ],
    likes: 0,
  },
  {
    id: 1417709,
    title: "Irish Slammer",
    image: "https://spoonacular.com/recipeImages/1417709-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 93619,
        amount: 1.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Alcoholic Beverages",
        name: "guinness stout",
        original: "1 Guinness stout draught",
        originalString: "1 Guinness stout draught",
        originalName: "Guinness stout draught",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/guinness.png",
      },
      {
        id: 93764,
        amount: 15.0,
        unit: "ml",
        unitLong: "milliliters",
        unitShort: "ml",
        aisle: "Alcoholic Beverages",
        name: "irish cream",
        original: "1/2 ounce (15ml) Bailey's Irish Cream Liqueur",
        originalString: "1/2 ounce (15ml) Bailey's Irish Cream Liqueur",
        originalName: "1/2 ounce Bailey's Irish Cream Liqueur",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/baileys-liqueur.png",
      },
    ],
    usedIngredients: [
      {
        id: 14052,
        amount: 15.0,
        unit: "ml",
        unitLong: "milliliters",
        unitShort: "ml",
        aisle: "Alcoholic Beverages",
        name: "whiskey",
        original:
          "1/2 ounce (15ml) Irish whiskey (like Proper no. Twelve or Jameson)",
        originalString:
          "1/2 ounce (15ml) Irish whiskey (like Proper no. Twelve or Jameson)",
        originalName:
          "1/2 ounce Irish whiskey (like Proper no. Twelve or Jameson)",
        metaInformation: ["(like Proper no. Twelve or Jameson)"],
        meta: ["(like Proper no. Twelve or Jameson)"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whiskey-bottle.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 0,
  },
];
